Added UriResolutionResult which can contain a value or error
polywrap/uri-resolver-extensions pull request #20
Opened 2023-03-17 22:51 UTC by nerfZael

One in the series of PRs to address: https://github.com/polywrap/toolchain/issues/663

2023-03-20 16:45 UTC, dOrgJelli requested changes

2023-03-20 16:45 UTC, dOrgJelli commented on interface/schema.graphql
> +  error: String
Can you please describe some scenarios when we'd want to use this error, instead of just `throw`ing an exception from within the resolver wrapper?

Basically, what are the differences in the following errors (1 & 2):
```typescript
const result = client.invoke<UriResolutionResult>(...);

// 1
if (!result.ok) {
  result.error
}

// 2
if (!result.value.ok) {
  result.value.error
}
```

2023-03-20 16:45 UTC, dOrgJelli commented on interface/schema.graphql
> +type UriResolutionResult {
For better backward compatibility, I'd suggest the following:
```graphql
type MaybeUriOrManifest  {
  uri: String
  manifest: String
  debug: String
}
```

This way you can write the calling logic as:
```typescript
const result = client.invoke<MaybeUriOrManifest>(...);

if (!result.ok) {
  // wrapper threw an error
  result.error
}

if (!result.value.uri && !result.value.manifest) {
  // resolution failed, look for debug info
  resolutionContext.addDebugInfo(
    result.value.debug
  );
}
```

2023-03-20 16:45 UTC, dOrgJelli commented
@nerfZael it might be helpful to add psuedo-code in this PR of what you expect the calling logic to look like (in the extendable uri resolver).

2023-03-25 04:37 UTC, dOrgJelli commented
Is this PR still relevant, or is it being replaced by #21 ?

2023-04-06 15:51 UTC, nerfZael commented
Closing this as there is another temporary solution: https://github.com/polywrap/uri-resolver-extensions/pull/21
We can revisit in the future and spec this out further

2023-04-06 15:51 UTC, closed without merging